name: Build APK

on:
  workflow_dispatch:
    inputs:
      release_tag:
        required: false
        type: string
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        fetch-depth: '0'

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Setup Android environment
      uses: android-actions/setup-android@v3

    - name: Decode Keystore
      uses: timheuer/base64-to-file@v1
      id: android_keystore
      with:
        fileName: "android_keystore.jks"
        encodedString: ${{ secrets.APP_KEYSTORE_BASE64 }}

    - name: Build APK
      run: |
        cd ${{ github.workspace }}/V2rayNG
        chmod 755 gradlew
        ./gradlew assembleRelease -Pandroid.injected.signing.store.file=${{ steps.android_keystore.outputs.filePath }} -Pandroid.injected.signing.store.password=${{ secrets.APP_KEYSTORE_PASSWORD }} -Pandroid.injected.signing.key.alias=${{ secrets.APP_KEYSTORE_ALIAS }} -Pandroid.injected.signing.key.password=${{ secrets.APP_KEY_PASSWORD }}

    - name: Debug APK files
      run: ls -R ${{ github.workspace }}/V2rayNG/app/build/outputs/apk/

    - name: Upload APKs as Artifacts
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: APKs
        path: ${{ github.workspace }}/V2rayNG/app/build/outputs/apk/**/*.apk

    - name: Upload to release
      uses: svenstaro/upload-release-action@v2
      if: github.event.inputs.release_tag != '' || github.ref == 'refs/heads/master'
      with:
        file: ${{ github.workspace }}/V2rayNG/app/build/outputs/apk/**/*.apk
        tag: ${{ github.event.inputs.release_tag || 'latest' }}
        file_glob: true
        prerelease: true
        repo_token: ${{ secrets.GITHUB_TOKEN }}
